### PR TITLE
Thermostat support

### PR DESCRIPTION
**Pull request by lassem**
Here's another PR for the thermostat support.

With this PR I have rebased onto what you had for 0.88+ and I've tried to keep the PR footprint to a minimum.

* Added support for thermostats.
* Added callback mechanism to update hass when device changes (by clicking physical buttons f.ex)
* Added some missing device ids which I had in my own setup.

### CODE REVIEW

**Comment by dbrouwer1979** [comment]
Hi! I have your PR working in my setup. I have not tested everything, but so far it is looking good!

**Comment by jheling** [comment]
Hello Lasse, Iam testing the new code with the callbacks. When activate a HW switch,  i don't see a change in the status of the light.  In the present situation , it works, the only drawback is the lag of several seconds. Does the callback mechanism work in your setup?

**Comment by jheling** [comment]
Hello Lasse,  I looked at the documentation and saw that you can send a True with self.async_update_ha_state. This forces a refresh. Now when I toggle a hw-button,  the status of the light in HA updates immediately. So it works!  
Can you add a True to all the sources in your pull request? Then I will import this pull in the main branch.

**Comment by lassem** [comment]
I'be been on vacation. I will update the PR right now.

**Comment by jheling** [comment]
Thank you, i have merged the pull request with the main branch

**Pull request merged**
